const mongoose=require("mongoose")
const markSchema=mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"studDatas"
    },
    subject1:{
        type:String,
        required:true
    },
    mark1:{
        type:String,
        required:true
    },
    subject2:{
        type:String,
        required:true
    },
    mark2:{
        type:String,
        required:true
    },
    subject3:{
        type:String,
        required:true
    },
    mark3:{
        type:String,
        required:true
    },
    subject4:{
        type:String,
        required:true
    },
    mark4:{
        type:String,
        required:true
    },
    subject5:{
        type:String,
        required:true
    },
    mark5:{
        type:String,
        required:true
    },
    
})
module.exports=mongoose.model("markDatas",markSchema)